const initialState = {
    openSidebar : true,
    token: localStorage.getItem('token'),
    isRegistered : false,
    isLoading: false,
    successMessage: "",
    errorMessage: "",
    isAuthenticated: "",
    user: "",
    userDetails:{},
    doctor:"",
    doctorId:"",
    hospitalId: "",
    isLoggedIn: false,
    link:"",
    resetToken: localStorage.getItem('resetToken'),
    hospitals: [],
    hospital: null,
    locationAccess: true,
    days: null,
    patientAppointmentValues: {},
    appointmentId: "",
    paidAppDetails:null,
    allPaidApp: null,
    patientMeetingDetails: null,
    doctorMeetingDetails: null,
    pMeetingId: "",
    dMeetingId: "",
    pwd:"",
    patientNotifications:"",
    patientNotification:"",
    patientNotificationAlert:"",
    doctorNotifications:"",
    doctorNotification:"",
    doctorNotificationAlert:"",
}

export default initialState;